- hosts: tracker
  remote_user: pi
  become: yes
  
  vars:
    vpn_server_address: trs.tricargo.de
    vpn_server_port: 1194
  
  tasks:
    - name: Uninstall man pages
      apt:
        name: manpages
        state: absent
        purge: yes
        
    - name: Update all packages
      apt:
        upgrade: yes
        update_cache: yes
  
    - name: Install OpenVPN client
      apt:
        name: openvpn
        state: latest
        
    - name: Create OpenVPN config directory
      file:
        path: /etc/openvpn
        state: directory
        
    - name: Copy OpenVPN config file
      template:
        src: vpn-config/client.conf
        dest: "/etc/openvpn"
        force: yes
      
      