---
- hosts: tracker
  tasks:
    
    - name: Ensure rc.local is there
      copy:
        src: files/etc/rc.local
        dest: /etc
        mode: 755
        owner: root
        group: root
      become: yes
      
    - name: Ensure wvdial configuration is there
      copy:
        src: files/etc/wvdial.conf
        dest: /etc
        mode: 0644
        owner: root
        group: root
      become: yes
      
    - name: Ensure network configuration is there
      copy:
        src: files/etc/network/interfaces
        dest: /etc/network
        mode: 0644
        owner: root
        group: root
      become: yes
        
    - name: Install at command
      package:
        name: at
        state: present
        
  