#! /bin/sh
### BEGIN INIT INFO
# Provides:          ttc-mqtt
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts Tricargo Telemetry Client (MQTT)
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
      start)
            start-mqtt
            ;;
      restart|reload|force-reload)
            echo "Error: argument '$1' not supported" >&2
            exit 3
            ;;
      stop)
            stop-mqtt
            ;;
      *)
            echo "Usage: $0 start|stop" >&2
            exit 3
            ;;
    esac
